### PR TITLE
WIP: Add appup, upgrade test suite

### PR DESCRIPTION
**Pull request by essen**
Ready for testing but should be squashed etc. before merge.

/cc @juhlig

### CODE REVIEW

**Comment by essen** [comment]
Note that "failures" currently only appear in the HTML logs.

**Comment by essen** [comment]
.appup documentation: http://erlang.org/doc/man/appup.html

**Comment by essen** [comment]
Force pushed with 3 cleaner commits. The PR is now at a point where it would benefit from #275 changes:

```
=ERROR REPORT==== 10-Feb-2020::14:01:18.920388 ===
Failed to start Ranch listener tcp_echo in ranch_tcp:listen(#{socket_opts => [{cacerts,'...'},{key,'...'},{cert,'...'},{port,5555}]}) for reason eaddrinuse (address already in use)

release_handler:install_release(Vsn="2" Opts=[{update_paths,true}]) failed, Reason={code_change_failed,
                                                                                    <0.127.0>,
                                                                                    ranch_acceptors_sup,
                                                                                    66312240012363923351599372627801158811,
                                                                                    {'EXIT',
                                                                                     {listen_error,
                                                                                      tcp_echo,
                                                                                      eaddrinuse}}}
```

I will therefore start adding #275 changes to this PR.

**Comment by essen** [comment]
So the big caveat is that #275 must exist in the release before the upgrade is performed, so that's going to make testing a little difficult.

**Comment by essen** [comment]
OK so the big hurdle right now is that `ranch_acceptor` processes get killed during the upgrade/downgrade and this brings down the whole application. What should be done is that Ranch stops the acceptors, loads the new module, then starts the acceptors again, or something to that effect.

**Comment by essen** [comment]
I've added a commit stopping and then restarting all acceptors during the upgrade process. The test now passes. @juhlig please review!

It would be good to confirm that all https://github.com/ninenines/ranch/pull/275 changes are actually necessary for this test to pass, and if not maybe we should have more tests. I can only confirm that the `ranch_acceptors_sup` changes are necessary at the moment because I saw the `eaddrinuse` error.

**Comment by essen** [comment]
Not sure why "TEMPORARY COMMIT" doesn't show up as the last commit, but note that it MUST be the last commit for the test suite to work, at the moment.

**Comment by juhlig** [comment]
I had test failures like `{badmatch, {error, closed}}` on line 183 the first few times I ran the test suite yesterday. Today, it worked. I believe that this may be a timout issue in the echo protocol (closes connection after 30s). Maybe we should put in an option for the echo protocol by which the timeout can be specified, and set it `$WAY_HIGH` for the upgrade test?

**Comment by juhlig** [comment]
> It would be good to confirm that all #275 changes are actually necessary for this test to pass, and if not maybe we should have more tests. I can only confirm that the `ranch_acceptors_sup` changes are necessary at the moment because I saw the `eaddrinuse` error.

I examined the changes from #275, and I don't think the changes in `ranch_listener_sup` are necessary. The call to `ranch_server:set_listener_sup` that it prevents on upgrade can actually be repeated, it will only lead to de- and instantly remonitoring that listener sup. It's similar to what happens if the listener sup crashes and the restart happens faster than the `DOWN` message.

**Comment by essen** [comment]
OK then let's remove the changes that are not necessary.

**Comment by juhlig** [comment]
> OK then let's remove the changes that are not necessary.

Ok, done in latest commit to #275

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
