### PR TITLE
Support new 18.0 options for SSL

### PR DESCRIPTION
**Pull request by ferd**
If this is acceptable, I can rebase the commits together.

### CODE REVIEW

**Comment by essen** [comment]
Yep looks fine, can squash.

**Comment by ferd** [comment]
Done.

**Comment by essen** [comment]
Done in 0d5d855da3d0b2d508fae4258b125a3a5ab7b306 along with many more options, and including documentation.

Currently still require cert or certfile only. Changing this will be done in 2.0.0 and is tracked by #112. I am not sure how wise it is to not set a default certificate to be honest, at least with sni_hosts. Sounds like the connection would abruptly close if the host the client sends doesn't match. More investigation is needed there.

**Comment by ferd** [comment]
Yeah, in our case we may have multiple certs for unrelated application. Serving a default one rather than closing abruptly is not acceptable as it means you're serving the wrong certs for given apps.

**Comment by essen** [comment]
Makes sense, will definitely be changed in 2.0.

**Pull request closed without merging**
