### PR TITLE
Extend error reason in case of failed handshake

### LINKED ISSUE #336: ranch:handshake(Ref) silently drops invalid TLS connections in ranch_ssl via exit(normal)
I am building a system with mutual certificate verification.
I'm using OTP-ized mode with ranch 2.0.0

```erlang
start_link(Ref, Transport, ProtoOpts) ->
    lager:debug("START_LINK ~p/~p/~p~n", [Ref, Transport, ProtoOpts]),
    {ok,
        proc_lib:spawn_link(?MODULE, init, [
            #{ref => Ref, transport => Transport, opts => ProtoOpts}
        ])}.

init(Arg) ->
    lager:info("INIT ~p~n", [Arg]),
    #{ref := Ref, transport := Tr} = Arg,
    case ranch:handshake(Ref) of
        {ok, Socket} ->
            lager:info("INIT handshake ~p~n", [Socket]),
            Tr:setopts(Socket, [{active, true}]),
            process_flag(trap_exit, true),
            gen_server:enter_loop(?MODULE, [], Arg#{sock => Socket});
        E ->
            lager:info("INIT failed ~p~n", [E])
    end.

% ...
```
It works beautifully for valid connections. It fails miserably for invalid connections. In the case of invalid connection (for example a failed TLS handshake), `ranch:handshake(Ref) ` does not return error, but does `exit(normal)` instead, which bypasses the rest of the function.

In particular, the function doesn't know _that_ the connection failed, not to mention _why_.

I partially circumvented the problem with **ugly** use of `catch`:

```erlang
init(Arg) ->
    lager:info("INIT ~p~n", [Arg]),
    #{ref := Ref, transport := Tr} = Arg,
    case catch ranch:handshake(Ref) of
        {ok, Socket} ->
            lager:info("INIT handshake ~p~n", [Socket]),
            Tr:setopts(Socket, [{active, true}]),
            process_flag(trap_exit, true),
            gen_server:enter_loop(?MODULE, [], Arg#{sock => Socket});
        {'EXIT', Reason} ->
            lager:error("INIT crashed ~p~n", [Reason]);
        E ->
            lager:info("INIT failed ~p~n", [E])
    end.
```
I know _that_ connection failed, but still have no idea _why_  (invalid cert, invalid protocol, other reason).

Is there a way to dig-out the exact cause of the error (and the IP of the failing party), or should I just switch to `ranch_tcp` and perform ssl/tls negotiation manually, in handler?

### PR DESCRIPTION
**Pull request by Maria-12648430**
Fixes #336.

### CODE REVIEW

**Comment by Maria-12648430** [comment]
About the pipeline failures in OTP 27: they happen because `ct_helper` apparently uses [`file:pid2name/1`](https://www.erlang.org/doc/man/file#pid2name-1), which has been deprecated and removed in OTP 27.

**Comment by essen** [comment]
No it's erlang.mk, it'll work if you `make erlang-mk` and commit the updated file.

**Comment by Maria-12648430** [comment]
Hm... and now there is a `badarg` returned from `ssl:connect/3` when used with a local address in OTP 27. Comparing the `ssl:connect` docs for OTP 26 and 27, it looks like support for local sockets was removed in 27 (it's `inet:socket_address() | inet:hostname()` in 26, but `gen_tcp:socket() | inet:hostname() | inet:ip_address()` in 27). I can't find anything in the change logs, though.

**Comment by Maria-12648430** [comment]
About the `ssl_local_echo` test currently failing for OTP 27, see https://github.com/erlang/otp/pull/8465

**Comment by juhlig** [comment]
Added a test. Also made a change to obtain the peername early in the handshake, as it could happen that it is not available any more when an error happens.

**Comment by essen** [comment]
I have updated the CI, please force push to run CI again.

**Comment by juhlig** [comment]
Done. There is a failure in the shutdown suite (macOS, again :roll_eyes:) which seems to be a timing issue, in the test.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
