### PR TITLE
Upstream sni

### PR DESCRIPTION
**Pull request by ferd**
Adding some annotations for 18.0+ options that were added to the SSL libs.

### CODE REVIEW

**Comment by essen** [comment]
Something is funky in the diff. The sni options are already there (with a less precise type I suppose) and yet the diff acts like they are not. Please remove the merge commit and/or rebase.

Also the backlog and send options are TCP options. See https://github.com/heroku/ranch/blob/f4d23d7128e89efcce323df3ef1979bfa1e8e917/src/ranch_ssl.erl#L83

**Comment by ferd** [comment]
UH alright. I'll double check that and re-open later.

**Comment by ferd** [comment]
Yeah you're right, just something that really went weird in there.

**Comment by essen** [comment]
Yeah... git is not supposed to do this. :-)

**Pull request closed without merging**
