### PR TITLE
Replace gen_server with gen_statem in examples

### PR DESCRIPTION
**Pull request by juhlig**
Issue #186

### CODE REVIEW

**Comment by essen** [comment]
Don't worry about the failures it's 21.0-rc1.

**Comment by juhlig** [comment]
ok :)

**Comment by essen** [comment]
```
=ERROR REPORT==== 4-May-2018::18:28:52 ===
** State machine <0.106.0> terminating
** Last event = {timeout,5000}
** When server state  = {connected,{state,#Port<0.484>,ranch_tcp}}
** Reason for termination = error:function_clause
** Callback mode = state_functions
** Stacktrace =
**  [{reverse_protocol,connected,
                       [timeout,5000,{state,#Port<0.484>,ranch_tcp}],
                       [{file,"src/reverse_protocol.erl"},{line,38}]},
     {gen_statem,call_state_function,5,[{file,"gen_statem.erl"},{line,1633}]},
     {gen_statem,loop_event_state_function,6,
                 [{file,"gen_statem.erl"},{line,1023}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

=ERROR REPORT==== 4-May-2018::18:28:52 ===
Ranch listener tcp_reverse had connection process started with reverse_protocol:start_link/4 at <0.106.0> exit with reason: {function_clause,[{reverse_protocol,connected,[timeout,5000,{state,#Port<0.484>,ranch_tcp}],[{file,"src/reverse_protocol.erl"},{line,38}]},{gen_statem,call_state_function,5,[{file,"gen_statem.erl"},{line,1633}]},{gen_statem,loop_event_state_function,6,[{file,"gen_statem.erl"},{line,1023}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

**Comment by juhlig** [comment]
Ah, I think I know where that comes from :/ Didn't notice because I never even waited for the timeout when trying it out. Will take care of it on monday.

**Comment by juhlig** [comment]
Should be fixed now.

**Comment by essen** [comment]
Merged, thanks! I had to change the arity of enter_loop which is 4 for gen_statem, otherwise just squashed.

**Pull request closed without merging**
