### PR TITLE
getstat support

### PR DESCRIPTION
**Pull request by juhlig**
getstat/{1,2} functions added to ranch_transport, _tcp, and _ssl as requested in issue #126 
also adds support for getopts/2 to ranch_transport, _tcp, and _ssl

### CODE REVIEW

**Comment by essen** [comment]
Seems good, just missing tests and documentation. :-)

**Comment by juhlig** [comment]
I'll see to it next week, this was (and still is) a very busy week.

**Comment by juhlig** [comment]
documentation was added. not sure if i have done this correctly, so please check

**Comment by essen** [comment]
It's good.

**Comment by juhlig** [comment]
great :) will add testsprobably on monday, then :)

**Comment by juhlig** [comment]
tests for getopts and getstat capabilities were added. test case for ssl:getstat/{1,2} skip when SSL version is <8.0, since according to [the SSL release notes](http://erlang.org/doc/apps/ssl/notes.html) is the version where getstat support was added

**Comment by essen** [comment]
Thanks. Afraid I'll have to take a look another time, it looks like I'm gonna need a few days off.

**Comment by juhlig** [comment]
sure, have a nice vacation then

**Comment by juhlig** [comment]
Just curious: what about this pull request? It's been created almost two months ago... Is it ok or should I change/fix something?

**Comment by essen** [comment]
I've been mostly sick or unavailable since my last message ("few" days off, hah). I haven't done much ticket-wise since then. I'll try to get on it on Wednesday.

**Comment by juhlig** [comment]
Oh, I'm sorry to hear that. Hope you get well soon.. No sweat then ;)

**Comment by essen** [comment]
Actually let me do this tomorrow on customer time, I think the customer in question would be interested in being able to pull socket stats easily.

**Comment by juhlig** [comment]
Sure

**Comment by essen** [comment]
Didn't manage to do it last week but here you go! Merged, thanks!

**Pull request closed without merging**
