### PR TITLE
allow keepalive option in ranch_tcp and ranch_ssl transports

### PR DESCRIPTION
**Pull request by gbour**
related to #108

### CODE REVIEW

**Comment by essen** [comment]
Alphabetical order on the list of options (at all 4 places you changed), thanks!

**Comment by gbour** [comment]
done :)

**Comment by gbour** [comment]
done :)

**Comment by essen** [comment]
Cool. Make that a single commit (git rebase -i HEAD^^^) and squash the right commit and it'll be merged as soon as Monday.

**Comment by voltone** [comment]
@gbour Any chance you can add 'ipv6_v6only' as well? Without it I cannot start listeners on the same port for IPv4 and IPv6. Assuming @essen doesn't have any objections...? Thanks!

**Comment by essen** [comment]
I don't have objections but you should probably send a PR directly. :-)

**Comment by voltone** [comment]
I was about to when I came across this issue, and I figured my PR would have a merge conflict with this one.

Would you consider a PR that changes socket option filtering to use a black-list rather than a white-list? I've ran into this issue a couple of times: first with the 'packet' option and then with 'keep-alive' (both of which shouldn't concern the listener socket, and I now set from my handler's init/4), and now with 'ipv6_v6only' (which cannot be set/changed after listen/2). I understand that some setting would interfere with the operation of the listener/acceptor logic in ranch, but it should be possible to filter out those. Maybe for v2?

**Comment by gbour** [comment]
@voltone I agree with @essen, you should fill a distinct PR.
@essen I merged commits, is it ok ?

**Comment by essen** [comment]
Yes, sorry been distracted with erlang.mk, it will be merged as soon as I'm done.

**Comment by essen** [comment]
Done in 0d5d855da3d0b2d508fae4258b125a3a5ab7b306 along with many more options, and including documentation.

@voltone I did not add ipv6_v6only yet, because I am a little confused by its description. What's the default value for example? True? I am assuming you want to set it to false?

**Pull request closed without merging**
