### PR TITLE
Add ipv6_v6only listen option.

### LINKED ISSUE #156: Extra inet listen option: ipv6_v6only
This option is used to listen on a inet6 port/address and not on a corresponding inet4 port.

Linux listens per default on both, which prevents separate inet4 and inet6 listeners.
BSD and some other system don't listen on both.
This option makes the listen code more portable.

I will make a merge request.

### PR DESCRIPTION
**Pull request by mworrell**
Fixes #156

### CODE REVIEW

**Comment by essen** [comment]
You forgot to update the docs.

**Comment by mworrell** [comment]
Good one! Will do so.

**Comment by mworrell** [comment]
@essen added some docs

**Comment by mworrell** [comment]
@essen Can you have a look at this one?  When merged we can remove our fork :)

**Comment by essen** [comment]
Squash the commits and I will merge during the day.

**Comment by mworrell** [comment]
Squashed and force pushed it.

**Comment by essen** [comment]
Merged, thanks!

**Comment by mworrell** [comment]
Thank you!

**Pull request closed without merging**
